language:
- c
- cpp

# clang is not supported for poppler
compiler: gcc

os: linux

sudo: false

addons:
  apt:
    packages:
    - cmake
    - libboost1.55-all-dev
    - libcppunit-dev
    - dvipng
    - texlive
    - liboverlay-scrollbar-0.2-dev
    - liblcms2-dev
    - libopenjpeg-dev
    - libjpeg-dev
    - fontconfig
    - librsvg2-dev
    - glade-gtk2
    - libglade2-dev
#    - libpoppler-dev
#    - libpoppler-cpp-dev
#    - libpoppler-glib-dev
    sources:
    - boost-latest
    - kalakris-cmake
  coverity_scan:
    project:
      name: "MarPiRK/xournalpp"
      description: "Notetaking software designed around a tablet."
    notification_email: marek@pikula.co
    build_command_prepend: "find .; mkdir build; cd build; cmake .. -DBUILD_POPPLER=ON -DEXT_GLIBMM=ON -DENABLE_MATHTEX=ON -DENABLE_OS=ON -DENABLE_CPPUNIT=ON -DUNSTABLE_LAYERS_SIDEBAR=ON"
    build_command: "make"
    branch_pattern: coverity_scan

#before_script:
#  - "mkdir build"
#  - "cd build"

#script:
#  - "cmake .. -DBUILD_POPPLER=ON -DEXT_GLIBMM=ON -DCMAKE_DEBUG_INCLUDES_LDFLAGS=ON -DENABLE_MATHTEX=ON -DENABLE_OS=ON -DENABLE_CPPUNIT=ON -DUNSTABLE_LAYERS_SIDEBAR=ON -DDEBUG_COMPILE=ON"
#  - "make"
#  - "ctest"
