language: cpp

compiler:
  - gcc
#  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libglibmm-2.4-dev libboost-all-dev glade-gtk2 libopenjpeg-dev
  - "wget https://launchpad.net/ubuntu/+source/cmake/2.8.8-2ubuntu1/+build/3441442/+files/cmake_2.8.8-2ubuntu1_amd64.deb"
  - "wget https://launchpad.net/ubuntu/+archive/primary/+files/cmake-data_2.8.8-2ubuntu1_all.deb"
  - "sudo apt-get remove cmake-data cmake"

install:
  - "sudo dpkg --install cmake-data_2.8.8-2ubuntu1_all.deb cmake_2.8.8-2ubuntu1_amd64.deb" 

before_script:
  - mkdir build
  - cd build

script:
  - cmake .. -DBUILD_BOOST:BOOST=ON -DCMAKE_COLOR_MAKEFILE:BOOL=OFF
  - make

os: linux

